---
- name: Configure pool
  hosts: '{{ host }}'
  become: yes
  become_method: sudo  
  gather_facts: false
  vars:
    env: lab
  remote_user: devops
  roles:
    - indy_node
  tags: [ 'pool', 'nodes' ]
