---
- name: Configure pool
  hosts: "{{ host | default('nodes') }}"
  become: yes
  become_method: sudo  
  gather_facts: false
  vars:
    env: lab
  roles:
    - indy_node
  tags: [ 'pool', 'nodes' ]
