@startuml
allow_mixing

title
    Pancanadian Indy Blockchain (Candy Blockchain). 
    Setting up Indy node, managed by different Canadian jurisdiction.
end title

caption Architecture of the Pancanadian Indy Blockchain

'Références graphique
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014

'Composants graphique
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Mobile/AzureNotificationHubs.puml
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/Users.puml
!includeurl AWSPuml/General/MobileClient.puml
!includeurl AWSPuml/General/InternetAlt2.puml
!includeurl AWSPuml/General/Client.puml
!includeurl AWSPuml/GroupIcons/ServerContents.puml
!includeurl AWSPuml/Blockchain/Blockchain.puml
!includeurl AWSPuml/Database/RDSPostgreSQLinstance.puml
!includeurl AWSPuml/GroupIcons/Cloud.puml
!includeurl AWSPuml/SecurityIdentityAndCompliance/IAMDataEncryptionKey.puml
!includeurl ICONURL/Concepts/link.puml

InternetAlt2(internet, "Internet", "")

'Observer Nodes
'Validator Nodes
'Tail Nodes
'   Initial Trustee (blockchain endpoint / genesis block)
'   Initial Steward (validator node endpoint)
'   Initial Endorsor (jurisdiction top level to create issuer)
node "Trust Registry - Pancanadian Blockchain" as candydlt {

    node "Node CAN" as NodeCA #LightGreen {
        Blockchain(dltCA, "Validator Node", "Registre de confiance") #LightBlue
        database "KMS Blockhain Wallet" as kmsCA #LightBlue
        ServerContents(serverCA, "CLI and Steward Monitoring Tools", "Bastion")
        AzureNotificationHubs(snsCA, "Notification", "Alertage") 
        ServerContents(TailCA, "Tail Node", "Registre de Révocation")
    }
}

node "Gouvernance Opérationnelle - Pancanadian Blockchain" as Gov {
    MobileClient(cellCA, "Mobile Employé", "appareil de l'employé") #LightBlue
    Users(EmployeCA, "Employé CA", "Sysadmin CA")

}

'DÉFINITION DES LIENS
internet --> dltCA
dltCA -down- kmsCA
serverCA -left- dltCA
snsCA -left- serverCA
snsCA --> Gov
cellCA --> EmployeCA
@enduml